const driversImage = {
  max_verstappen: "https://i.ibb.co/sWCK61x/VER.png",
  norris: "https://i.ibb.co/gRg1ypr/NOR.png",
  leclerc: "https://i.ibb.co/WK0JwqX/LEC.png",
  sainz: "https://i.ibb.co/HnLnkxJ/SAI.png",
  perez: "https://i.ibb.co/str11CC/PER.png",
  piastri: "https://i.ibb.co/qWvj6Mn/PIA.png",
  russell: "https://i.ibb.co/N16kHDJ/RUS.png",
  alonso: "https://i.ibb.co/NmSGMsN/ALO.png",
  tsunoda: "https://i.ibb.co/7Wc2bbS/TSU.png",
  stroll: "https://i.ibb.co/ZB5d5dS/STR.png",
  ricciardo: "https://i.ibb.co/nQ2rcLx/RIC.png",
  bearman: "https://i.ibb.co/nL7tjp9/BEA.png",
  hulkenberg: "https://i.ibb.co/Mg5Dq5Y/HUL.png",
  gasly: "https://i.ibb.co/JmrJ3zD/GAS.png",
  ocon: "https://i.ibb.co/qs3gWQM/OCO.png",
  albon: "https://i.ibb.co/hXHtnQy/ALB.png",
  kevin_magnussen: "https://i.ibb.co/kqLkwk8/MAG.png",
  zhou: "https://i.ibb.co/cFLK4QX/ZHO.png",
  bottas: "https://i.ibb.co/py1DKp1/BOT.png",
  sargeant: "https://i.ibb.co/Zm4xrsC/SAR.png",
  hamilton: "https://i.ibb.co/LYRRSqh/HAM.png",
};

export default driversImage;
