const driversImage2 = {
  max_verstappen: "https://i.ibb.co/sWCK61x/VER.png",
  norris: "https://i.ibb.co/QFDL6LT/NORv2.png",
  leclerc: "https://i.ibb.co/nCwmV45/LECv2.png",
  sainz: "https://i.ibb.co/Tk6DGhL/SAIv2.png",
  perez: "https://i.ibb.co/nz4bnz6/PERv2.png",
  piastri: "https://i.ibb.co/n194c1K/PIAv2png.png",
  russell: "https://i.ibb.co/N16kHDJ/RUS.png",
  alonso: "https://i.ibb.co/MP5xtDs/ALOv2.png",
  tsunoda: "https://i.ibb.co/4Tfgd10/TSUv2.png",
  stroll: "https://i.ibb.co/CBgGkbn/STR.png",
  ricciardo: "https://i.ibb.co/QkK2x4N/RICv2.png",
  bearman: "https://i.ibb.co/nL7tjp9/BEA.png",
  hulkenberg: "https://i.ibb.co/k1MKbG1/HULv2.png",
  gasly: "https://i.ibb.co/hBcYF5W/GASv2.png",
  ocon: "https://i.ibb.co/9Ws6ktN/OCOv2.png",
  albon: "https://i.ibb.co/9bQfckw/ALBv2.png",
  kevin_magnussen: "https://i.ibb.co/sF2C78j/MAGv2.png",
  zhou: "https://i.ibb.co/pK97TBL/ZHOv2.png",
  bottas: "https://i.ibb.co/5xD2HxH/BOTv2.png",
  sargeant: "https://i.ibb.co/HVSsvS8/SARv2.png",
  hamilton: "https://i.ibb.co/xmT0DWZ/HAMv2.png",
};

export default driversImage2;
